global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'falachefe-crewai'
    environment: 'production'

# Alertmanager (opcional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API CrewAI
  - job_name: 'crewai-api'
    static_configs:
      - targets: ['crewai-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

