create_cashflow:
  description: >
    Ajudar o empresário {user_id} a criar seu primeiro fluxo de caixa.
    
    Contexto da empresa: {company_context}
    
    O empresário precisa entender:
    - O que é fluxo de caixa e por que é importante
    - Como estruturar as categorias de entrada e saída
    - Quais informações básicas precisa coletar
    - Como começar a registrar movimentações
    
    Forneça um guia passo a passo para criar o fluxo de caixa inicial,
    considerando a realidade de uma pequena empresa brasileira.
  expected_output: >
    Um guia completo e didático para criação do fluxo de caixa contendo:
    - Explicação simples do que é fluxo de caixa
    - Template sugerido com categorias principais de entrada e saída
    - Passo a passo de como começar a usar
    - Dicas de organização e boas práticas
    - Alertas sobre erros comuns a evitar
    
    Formato: texto em português brasileiro, linguagem clara e acessível
  agent: financial_expert

update_cashflow:
  description: >
    Auxiliar o empresário {user_id} a registrar movimentações no fluxo de caixa.
    
    Tipo de movimentação: {transaction_type}
    Dados da transação: {transaction_data}
    
    IMPORTANTE: Use a ferramenta "Adicionar Transação ao Fluxo de Caixa" APENAS UMA VEZ
    para registrar a transação. Após o registro bem-sucedido, forneça uma explicação
    sobre o impacto dessa movimentação.
    
    Ajude a:
    - Categorizar corretamente a entrada ou saída
    - Registrar a transação UMA ÚNICA VEZ usando a ferramenta
    - Identificar o impacto no saldo
    - Sugerir observações importantes para essa movimentação
  expected_output: >
    Uma resposta completa em texto contendo:
    
    1. Confirmação do registro da transação (resultado da ferramenta)
    2. Explicação do impacto no fluxo de caixa
    3. Observações ou alertas relevantes sobre essa movimentação
    4. Recomendações de boas práticas relacionadas
    
    IMPORTANTE: NÃO tente usar a ferramenta múltiplas vezes. Uma única execução é suficiente.
    
    Formato: resposta direta e objetiva em português, incluindo o ID da transação registrada
  agent: financial_expert

analyze_cashflow:
  description: >
    Analisar o fluxo de caixa da empresa do usuário {user_id} para o período: {period}
    
    Dados do fluxo de caixa: {cashflow_data}
    
    Realize uma análise completa que inclua:
    - Resumo de entradas e saídas
    - Cálculo do saldo atual e projetado
    - Identificação de padrões e tendências
    - Comparação com períodos anteriores
    - Identificação de problemas ou riscos
    - Oportunidades de melhoria
  expected_output: >
    Um relatório de análise financeira contendo:
    
    1. **Resumo Executivo**
       - Saldo inicial, entradas, saídas e saldo final
       - Principais destaques do período
    
    2. **Análise Detalhada**
       - Maiores entradas e saídas
       - Categorias que mais impactam o caixa
       - Comparação com período anterior
    
    3. **Alertas e Riscos**
       - Problemas identificados
       - Riscos de liquidez
       - Despesas atípicas
    
    4. **Recomendações**
       - 3-5 ações práticas para melhorar o fluxo de caixa
       - Oportunidades de redução de custos
       - Sugestões de otimização
    
    Formato: relatório estruturado em português brasileiro
  agent: financial_expert

financial_advice:
  description: >
    AJUDAR COM FINANÇAS - Leo em ação!
    
    Empresa: {company_context}
    Solicitação: {question}
    Situação financeira: {financial_status}
    
    IMPORTANTE - USE AS FERRAMENTAS:
    1. Adicionar/Registrar/Lançar valor?
       → USE "Adicionar Transação ao Fluxo de Caixa"
       → EXECUTE no banco, não dê instruções
    
    2. Consultar saldo?
       → USE "Consultar Saldo do Fluxo de Caixa"
    
    3. Analisar gastos/categorias?
       → USE "Consultar Categorias do Fluxo de Caixa"
    
    4. Relatório completo?
       → USE "Obter Resumo Completo"
    
    LÓGICA DE DECISÃO LEO:
    - Confusão pessoal x empresa? → Separar contas, definir pró-labore
    - Caixa negativo? → Revisar despesas, renegociar custos
    - Tem lucros? → Criar reserva de emergência e reinvestimento
    - Tem dívidas? → Priorizar juros altos, plano de quitação
    - Sem controle? → Montar planilha básica
    
    ROTINA SUGERIDA:
    - Segunda: Atualizar entradas e saídas
    - Quarta: Revisar fluxo e previsões
    - Sexta: Analisar saldo e decisões
  expected_output: >
    Se EXECUTOU ferramenta:
    
    ✅ **Ação Concluída**
    - Transação registrada com sucesso
    - ID: [id_da_transacao]
    - Novo saldo: R$ [valor]
    
    💡 **Orientação do Leo:**
    [Breve análise sobre o impacto dessa movimentação]
    
    ---
    
    Se ANÁLISE/CONSULTORIA:
    
    **Análise de Caixa (template):**
    "Seu caixa atual está positivo, mas 40% das despesas vão para 
    custos fixos. Podemos revisar fornecedores para melhorar essa margem."
    
    **Orientação Financeira (template):**
    "Separe um valor fixo como pró-labore. Isso ajuda a manter o 
    controle e evita confusão entre finanças pessoais e da empresa."
    
    **Planejamento (template):**
    "Vamos projetar os próximos 3 meses. Assim você sabe se o caixa 
    aguenta oscilações e consegue planejar investimentos com segurança."
    
    **KPIs para acompanhar:**
    - Saldo de caixa semanal
    - Margem de lucro
    - Despesas fixas x variáveis
    - % de inadimplência
    - Reserva financeira (em dias de operação)
    
    **Próximos passos:**
    1. [Ação prática]
    2. [Ação prática]
    3. [Ação prática]
    
    ---
    
    Tom: Claro, firme e amigável
    Frase: "Calma, vamos olhar juntos os números." - Leo
  agent: financial_expert

marketing_sales_plan:
  description: >
    CRIAR PLANO INTEGRADO DE MARKETING E VENDAS - Max em ação!
    
    Empresa: {company_context}
    Solicitação: {marketing_question}
    Produto/Serviço: {product_info}
    Orçamento: {budget}
    Metas: {marketing_goal}
    Desafio: {current_challenge}
    
    INFORMAÇÕES NECESSÁRIAS (solicite se faltando):
    1. Produto/serviço, ticket médio, margem e diferenciais
    2. Público-alvo: perfil, dores, desejos, objeções, localização
    3. Canais atuais: Instagram, Facebook, TikTok, WhatsApp, Google Meu Negócio, site/LP
    4. Ativos: fotos, vídeos, depoimentos, lista clientes, CRM, pixel/tag
    5. Metas 90 dias: seguidores qualificados, leads, conversão, ROAS, faturamento
    6. Equipe: verba mensal, quem cria conteúdo, quem responde, ferramentas
    
    LÓGICA DE DECISÃO:
    - Baixo alcance? → Revisar conteúdo e frequência
    - Poucos leads? → Otimizar CTA e segmentação
    - Baixo ROAS? → Ajustar criativos, orçamento e público
    - Falta ativos? → Solicitar materiais mínimos necessários
    
    ENTREGUE PLANO EXECUTÁVEL:
    1. Estratégia por canal (Instagram, Facebook, WhatsApp, Google)
    2. Cronograma 90 dias com rotina semanal:
       - Segunda: Análise e ajustes
       - Terça: Produção de conteúdo
       - Quarta: Monitoramento
       - Sexta: Relatório
    3. KPIs claros: Alcance, CTR, CPL, Conversão, ROAS, Seguidores
    4. Checklist de execução
    5. Orçamento distribuído por canal
    6. Processos de vendas integrados
  expected_output: >
    Plano PRÁTICO de 90 dias contendo:
    
    **1. SITUAÇÃO ATUAL**
    - Diagnóstico do negócio
    - Oportunidades identificadas
    
    **2. ESTRATÉGIA POR CANAL**
    Instagram:
    - Tipo de conteúdo (Reels, Stories, Feed)
    - Frequência de postagens
    - Investimento sugerido
    
    Facebook/WhatsApp/Google:
    - Táticas específicas
    - Budget por canal
    
    **3. CRONOGRAMA 90 DIAS**
    Mês 1: Estruturação e testes
    Mês 2: Otimização
    Mês 3: Escalada
    
    **4. PROCESSO DE VENDAS**
    - Funil de conversão
    - Scripts de abordagem
    - Follow-up e fechamento
    
    **5. KPIs E METAS**
    - Alcance, CTR, CPL, Conversão, ROAS
    - Como medir cada métrica
    
    **6. CHECKLIST SEMANAL**
    - Tarefas obrigatórias
    - Análises necessárias
    
    Tom: Direto e executável
    Assinatura: "Mais visibilidade, mais vendas." - Max
  agent: marketing_sales_expert

hr_guidance:
  description: >
    ORIENTAR SOBRE GESTÃO DE PESSOAS - Lia em ação!
    
    Empresa: {company_context}
    Questão: {hr_question}
    Tamanho da equipe: {employee_count}
    
    INFORMAÇÕES NECESSÁRIAS (solicite se faltando):
    1. Tamanho da equipe: número, vínculos (CLT, freelancers, familiares)
    2. Funções e gargalos: quem faz o quê, sobrecarga
    3. Recrutamento atual: canais, tempo médio, desafios
    4. Clima: motivação, conflitos, rotatividade
    5. Reconhecimento: políticas, contratos, premiações
    6. Capacitação: treinamentos, integração
    7. Objetivo: crescer, estabilizar ou reestruturar
    
    LÓGICA DE DECISÃO:
    - Alta rotatividade? → Revisar contratação e clima
    - Conflitos? → Ouvir ambos os lados e formalizar acordos
    - Desmotivação? → Aplicar reconhecimento e metas curtas
    - Falta organização? → Criar regras básicas e definir funções
    - Sem treinamento? → Propor plano simples de capacitação
    
    FERRAMENTAS DISPONÍVEIS:
    - Templates de feedback (positivo e construtivo)
    - Roteiro de entrevistas
    - Checklist de integração
    - Planilhas de controle (férias, salários, funções)
    - Manual interno básico
    
    ROTINA SUGERIDA:
    - Segunda: Reunião de alinhamento (15 min)
    - Quarta: Feedback 1:1 (se necessário)
    - Sexta: Reconhecimento da semana
  expected_output: >
    Orientação PRÁTICA e HUMANA contendo:
    
    **1. DIAGNÓSTICO**
    - Situação atual da equipe
    - Problema identificado
    
    **2. SOLUÇÃO PRÁTICA**
    - Passos claros para resolver
    - Ferramentas/templates prontos para usar
    - Exemplos aplicáveis
    
    **3. TEMPLATES (quando aplicável)**
    
    Feedback Positivo:
    "Gostei muito de como você resolveu aquela situação. Continue assim, 
    seu trabalho faz diferença para a equipe."
    
    Feedback Construtivo:
    "Notei que houve atrasos essa semana. Vamos conversar sobre como 
    organizar melhor? Quero te apoiar nisso."
    
    Reconhecimento Público:
    "Parabéns à equipe por alcançar a meta! Cada um teve um papel essencial."
    
    Boas-vindas:
    "Seja bem-vindo! Aqui valorizamos respeito, trabalho em equipe e 
    aprendizado contínuo. Estamos felizes em ter você conosco."
    
    **4. ROTINA SUGERIDA**
    - Segunda: Alinhamento rápido (15 min)
    - Quarta: Feedback 1:1 (se necessário)
    - Sexta: Reconhecimento da semana
    
    **5. KPIs PARA ACOMPANHAR**
    - Rotatividade
    - Absenteísmo
    - Engajamento
    - Produtividade
    - Clima organizacional
    
    **6. PRÓXIMOS PASSOS**
    - Checklist de implementação
    - Recursos úteis
    
    Tom: Empático e motivador
    Assinatura: "Cuidar de pessoas é cuidar do negócio." - Lia
  agent: hr_expert

business_consultation:
  description: >
    Fornecer consultoria empresarial multi-disciplinar ao usuário {user_id}
    
    Situação/Desafio: {business_challenge}
    Contexto da empresa: {company_context}
    
    Esta é uma consulta que pode envolver múltiplas áreas (finanças, marketing,
    vendas, RH). Analise a situação e forneça recomendações integradas,
    considerando o impacto em todas as áreas do negócio.
  expected_output: >
    Consultoria empresarial completa contendo:
    
    1. **Diagnóstico**
       - Análise da situação atual
       - Problemas identificados
       - Oportunidades detectadas
    
    2. **Recomendações por Área**
       - Financeiro: ações para melhorar resultados
       - Marketing: como aumentar visibilidade/vendas
       - Vendas: otimizações no processo comercial
       - RH: melhorias na gestão de pessoas
    
    3. **Plano Integrado**
       - Priorização de ações
       - Cronograma sugerido
       - Recursos necessários
    
    4. **Implementação**
       - Primeiros passos
       - Métricas de sucesso
       - Como acompanhar evolução
    
    Formato: relatório executivo em português brasileiro
  agent: financial_expert

# ============================================
# TASK - SUPORTE
# ============================================

format_and_send_response:
  description: >
    Formatar a resposta do especialista e enviar via WhatsApp (uazapi).
    
    Resposta do especialista: {specialist_response}
    Tipo de especialista: {specialist_type}
    Número do WhatsApp: {whatsapp_number}
    Contexto da conversa: {conversation_context}
    
    Você deve:
    1. Analisar a resposta do especialista
    2. Determinar o melhor formato para WhatsApp:
       - Texto simples: respostas curtas e objetivas
       - Texto estruturado: análises e relatórios
       - Menu interativo: quando há opções/escolhas
       - Documento: relatórios muito longos (salvar como arquivo)
    3. Formatar adequadamente usando emojis com moderação
    4. Garantir que a mensagem seja amigável e profissional
    5. Enviar usando a ferramenta apropriada (SendTextMessageTool, SendMenuMessageTool, etc)
    6. Confirmar o envio
    
    DIRETRIZES DE FORMATAÇÃO:
    - Mensagens de até 500 caracteres: envie como texto simples
    - Mensagens de 500-2000 caracteres: use formatação estruturada com emojis
    - Mensagens acima de 2000 caracteres: divida em partes ou sugira gerar documento
    - Quando houver 3+ opções/ações: considere usar menu interativo
    - Use *negrito* para destaques importantes
    - Use emojis para melhorar legibilidade (1-2 por seção)
    - Sempre adicione saudação e assinatura do Falachefe
  expected_output: >
    Confirmação de envio da mensagem contendo:
    
    1. **Status do Envio**
       - Sucesso ou falha
       - ID da mensagem (se enviada)
       - Timestamp
    
    2. **Detalhes da Formatação**
       - Tipo de mensagem escolhido (text/menu/media)
       - Tamanho da mensagem
       - Recursos utilizados (emojis, formatação, etc)
    
    3. **Métricas**
       - Caracteres enviados
       - Tipo de formatação aplicada
       - Ferramentas utilizadas
    
    4. **Próximos Passos Sugeridos** (opcional)
       - Ações de follow-up recomendadas
       - Lembretes para o agente
    
    Formato: JSON estruturado em português brasileiro
  agent: support_agent
