version: '3.8'

# ===========================================
# VERSÃO MÍNIMA - APENAS API CREWAI
# ===========================================
# Use este arquivo se não precisar de Redis, PostgreSQL, Nginx, etc.
# Para rodar: docker-compose -f docker-compose.minimal.yml up -d

services:
  crewai-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falachefe-crewai-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - UAZAPI_BASE_URL=${UAZAPI_BASE_URL:-https://falachefe.uazapi.com}
      - UAZAPI_TOKEN=${UAZAPI_TOKEN}
      - UAZAPI_ADMIN_TOKEN=${UAZAPI_ADMIN_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
      - GUNICORN_THREADS=${GUNICORN_THREADS:-4}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-120}
    volumes:
      - ./logs:/app/logs
      - ./knowledge:/app/knowledge:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

